name: autotools
# autotools build of tesseract and training tools on ubuntu, macos homebrew and macports.
on:
  push:
  schedule:
    - cron: 0 20 * * *

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: ubuntu-18.04-clang-7-cmake-build, os: ubuntu-18.04, cc: clang-7,  cxx: clang++-7 }
          - { name: ubuntu-18.04-clang-8-cmake-build, os: ubuntu-18.04, cc: clang-8,  cxx: clang++-8 } #installed
          - { name: ubuntu-18.04-clang-9-cmake-build, os: ubuntu-18.04, cc: clang-9,  cxx: clang++-9 } #installed
          - { name: ubuntu-18.04-clang-10-cmake-build, os: ubuntu-18.04, cc: clang-10,  cxx: clang++-10 }
          
          - { name: ubuntu-18.04-gcc-7-cmake-build, os: ubuntu-18.04, cc: gcc-7,  cxx: g++-7 } #installed
          - { name: ubuntu-18.04-gcc-8-cmake-build, os: ubuntu-18.04, cc: gcc-8,  cxx: g++-8 } #installed
          - { name: ubuntu-18.04-gcc-9-cmake-build, os: ubuntu-18.04, cc: gcc-9,  cxx: g++-9 } #installed
          - { name: ubuntu-18.04-gcc-10-cmake-build, os: ubuntu-18.04, cc: gcc-10,  cxx: g++-10 } #installed
          
          - { name: ubuntu-20.04-clang-7-cmake-build, os: ubuntu-20.04, cc: clang-7, cxx: clang++-7 }
          - { name: ubuntu-20.04-clang-8-cmake-build, os: ubuntu-20.04, cc: clang-8, cxx: clang++-8 } #installed
          - { name: ubuntu-20.04-clang-9-cmake-build, os: ubuntu-20.04, cc: clang-9, cxx: clang++-9 } #installed
          - { name: ubuntu-20.04-clang-10-cmake-build, os: ubuntu-20.04, cc: clang-10, cxx: clang++-10 } #installed
          
          - { name: ubuntu-20.04-gcc-7-cmake-build, os: ubuntu-20.04, cc: gcc-7, cxx: g++-7 } #installed
          - { name: ubuntu-20.04-gcc-8-cmake-build, os: ubuntu-20.04, cc: gcc-8, cxx: g++-8 } #installed
          - { name: ubuntu-20.04-gcc-9-cmake-build, os: ubuntu-20.04, cc: gcc-9, cxx: g++-9 } #installed
          - { name: ubuntu-20.04-gcc-10-cmake-build, os: ubuntu-20.04, cc: gcc-10, cxx: g++-10 } #installed

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Compiler
      run: |
           sudo apt-get install -y ${{ matrix.config.cxx }} ${{ matrix.config.cc }}
        
    - name: Install dependencies
      run: |
           sudo apt-get install autoconf-archive libleptonica-dev libpango1.0-dev -y

    - name: Setup
      run: |
           mkdir -p m4
           ./autogen.sh

    - name: Configure
      run: |
           ./configure '--disable-shared' 'CXX=${{ matrix.config.cxx }}' 'CXXFLAGS=-g -O2'
      
    - name: Make and Install Tesseract
      run: |
           make -j 8
           sudo make install install

    - name: Make and Install Training Tools
      run: |
           make training -j 8
           sudo make install training-install
      
    - name: Display Tesseract and Training Tools Version
      run: |
           tesseract -v
           lstmtraining -v
           text2image -v
      if: success() || failure()
        
    - name: Download fonts, tessdata and langdata required for tests
      run: |
           git clone https://github.com/egorpugin/tessdata tessdata_unittest
           cp tessdata_unittest/fonts/* test/testing/ 
           mv tessdata_unittest/* ../
      
    - name: Run Tesseract on phototest.tif and raaj.tif
      run: |
           tesseract test/testing/phototest.tif -  --tessdata-dir ../tessdata
           tesseract test/testing/raaj.tif - -l hin  --tessdata-dir ../tessdata
           cd cmaketest
           ${{ matrix.config.cxx }} basicapitest.cpp `pkg-config --cflags --libs tesseract lept ` -fopenmp  -pthread -o basicapitest 
           
    - name: Display Compiler Version
      run: |
           ${{ matrix.config.cxx }} --version
           git log -3 --pretty=format:'%h %ad %s | %an' 
      if: always()

  homebrew:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: macos-10.15-clang-12-cmake-build, os: macos-10.15, cc: clang, cxx: clang++ } # defualt clang-12
          - { name: macos-10.15-clang-11-cmake-build, os: macos-10.15, cc: '$(brew --prefix llvm)/bin/clang', cxx: '$(brew --prefix llvm)/bin/clang++' }  #installed llvm-11
          - { name: macos-10.15-gcc-8-cmake-build, os: macos-10.15, cc: gcc-8, cxx: g++-8 } #installed
          - { name: macos-10.15-gcc-9-cmake-build, os: macos-10.15, cc: gcc-9, cxx: g++-9 } #installed
          - { name: macos-10.15-gcc-10-cmake-build, os: macos-10.15, cc: gcc-10, cxx: g++-10 } #installed
        
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
           
    - name: install dependencies
      run: |
           brew install automake autoconf-archive
           brew install libarchive
           brew install leptonica
           brew install cairo pango
                      
    - name: Setup
      run: |
           mkdir -p m4
           ./autogen.sh
        
    - name: Configure
      run: |
           ./configure '--disable-shared' '--with-pic' 'CXX=${{ matrix.config.cxx }}' 'CXXFLAGS=-g -O2' 'PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig'
        
    - name: Make and Install Tesseract
      run: |
           make -j 8
           sudo make install install

    - name: Make and Install Training Tools
      run: |
           make training -j 8
           sudo make install training-install

    - name: Display Tesseract and Training Tools Version
      run: |
           ${{ matrix.config.cxx }} --version
           tesseract -v
           lstmtraining -v
           text2image -v
      if: success() || failure()
        
    - name: Get fonts, tessdata and langdata required for unit tests
      run: |
           git clone https://github.com/egorpugin/tessdata tessdata_unittest
           cp tessdata_unittest/fonts/* test/testing/
           mv tessdata_unittest/* ../
            
    - name: Run Tesseract on phototest.tif and raaj.tif
      run: |
           tesseract test/testing/phototest.tif -  --tessdata-dir ../tessdata
           tesseract test/testing/raaj.tif - -l hin  --tessdata-dir ../tessdata
           cd cmaketest
           ${{ matrix.config.cxx }} basicapitest.cpp `pkg-config --cflags --libs tesseract lept ` -fopenmp  -pthread -o basicapitest 
           
    - name: Display Compiler Version
      run: |
           ${{ matrix.config.cxx }} --version
           git log -3 --pretty=format:'%h %ad %s | %an' 
      if: always()

  macports:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: macos-10.15-clang-12-cmake-build, os: macos-10.15, cc: clang, cxx: clang++ } # defualt
          - { name: macos-10.15-clang-11-cmake-build, os: macos-10.15, cc: '$(brew --prefix llvm)/bin/clang', cxx: '$(brew --prefix llvm)/bin/clang++' }  #installed
          - { name: macos-10.15-gcc-8-cmake-build, os: macos-10.15, cc: gcc-8, cxx: g++-8 } #installed
          - { name: macos-10.15-gcc-9-cmake-build, os: macos-10.15, cc: gcc-9, cxx: g++-9 } #installed
          - { name: macos-10.15-gcc-10-cmake-build, os: macos-10.15, cc: gcc-10, cxx: g++-10 } #installed
        
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install Macports
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci; source ./macports-ci install

    - name: Install Dependencies
      run: |
           sudo port install \
                  autoconf autoconf-archive \
                  automake \
                  libtool \
                  pkgconfig \
                  leptonica 
           sudo port install cairo pango 
           sudo port install icu +devel
        
    - name: Setup
      run: |
           mkdir -p m4
           ./autogen.sh
        
    - name: Configure
      run: |
           ./configure  '--disable-shared' '--with-pic' 'CXX=${{ matrix.config.cxx }}' 'CXXFLAGS=-g -O2' 
        
    - name: Make and Install Tesseract
      run: |
           make -j 8
           sudo make install install

    - name: Make and Install Training Tools
      run: |
           make training -j 8
           sudo make install training-install
      
    - name: Display Version
      run: |
           tesseract -v
           lstmtraining -v
           text2image -v
      if: success() || failure()

    - name: Get fonts, tessdata and langdata required for unit tests
      run: |
           git clone https://github.com/egorpugin/tessdata tessdata_unittest
           cp tessdata_unittest/fonts/* test/testing/
           mv tessdata_unittest/* ../
      
    - name: Run Tesseract on phototest.tif and raaj.tif
      run: |
           tesseract test/testing/phototest.tif -  --tessdata-dir ../tessdata
           tesseract test/testing/raaj.tif - -l hin  --tessdata-dir ../tessdata
           cd cmaketest
           ${{ matrix.config.cxx }} basicapitest.cpp `pkg-config --cflags --libs tesseract lept ` -fopenmp  -pthread -o basicapitest 
           ./basicapitest
           
    - name: Display Compiler Version
      run: |
           ${{ matrix.config.cxx }} --version
           git log -3 --pretty=format:'%h %ad %s | %an' 
      if: always()
