name: vcpkg
# cmake build of tesseract and training tools using vcpkg.
# Building training tools without sw is not supported on windows with cmake.
# Build stable version 4.1.1. 
# Requested port update https://github.com/microsoft/vcpkg/issues/16019.
on:
  #push:
  schedule:
    - cron: 0 0 2 3 *
jobs: 
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Checkout vcpkg
      run: |
           git clone https://github.com/microsoft/vcpkg
    
    - name: Install vcpkg (Linux)
      run: |
           vcpkg/bootstrap-vcpkg.sh
           vcpkg/vcpkg integrate install
           vcpkg/vcpkg list tess
      if: runner.os == 'Linux'
    
    - name: Build Tesseract Dependencies (Linux)
      run: |
           vcpkg/vcpkg install bzip2[core]:x64-linux giflib[core]:x64-linux leptonica[core]:x64-linux libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-linux libiconv[core]:x64-linux libjpeg-turbo[core]:x64-linux liblzma[core]:x64-linux libpng[core]:x64-linux libwebp[core,nearlossless,simd]:x64-linux libxml2[core]:x64-linux lz4[core]:x64-linux lzo[core]:x64-linux openjpeg[core]:x64-linux openssl[core]:x64-linux tiff[core]:x64-linux xxhash[core]:x64-linux zlib[core]:x64-linux zstd[core]:x64-linux
      if: runner.os == 'Linux'
    
    - name: Build Tesseract 4.1.1 (Linux)
      run: |
           vcpkg/vcpkg install tesseract:x64-linux
      if: runner.os == 'Linux'
    
    - name: Build baseapitest (Linux)
      run: |
           mkdir test-build && cd test-build
           cmake ../cmaketest 
           cmake --build . 
           ./basicapitest
      if: runner.os == 'Linux'
    
    - name: Build (macOS)
      run: |
           vcpkg/bootstrap-vcpkg.sh
           vcpkg/vcpkg integrate install
           vcpkg/vcpkg list tess
      if: runner.os == 'macOS'
    
    - name: Build Tesseract Dependencies (macOS)
      run: |
           vcpkg/vcpkg install bzip2[core]:x64-osx giflib[core]:x64-osx leptonica[core]:x64-osx libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-osx libiconv[core]:x64-osx libjpeg-turbo[core]:x64-osx liblzma[core]:x64-osx libpng[core]:x64-osx libwebp[core,nearlossless,simd]:x64-osx libxml2[core]:x64-osx lz4[core]:x64-osx lzo[core]:x64-osx openjpeg[core]:x64-osx openssl[core]:x64-osx tiff[core]:x64-osx xxhash[core]:x64-osx zlib[core]:x64-osx zstd[core]:x64-osx
      if: runner.os == 'macOS'
    
    - name: Build Tesseract 4.1.1 (macOS)
      run: |
           vcpkg/vcpkg install tesseract:x64-osx
      if: runner.os == 'macOS'
    
    - name: Build baseapitest (macOS)
      run: |
           mkdir test-build && cd test-build
           cmake ../cmaketest 
           cmake --build . 
           ./basicapitest
      if: runner.os == 'macOS'
    
    - name: Build (Windows)
      run: |
           vcpkg/bootstrap-vcpkg.bat
           vcpkg/vcpkg integrate install
           vcpkg/vcpkg list tess
           vcpkg/vcpkg install tesseract:x64-windows
      if: runner.os == 'Windows'
    