name: vcpkg
# cmake build of tesseract and training tools using vcpkg.
# Building training tools without sw is not supported on windows with cmake.
# Build stable version 4.1.1. 
# Requested port update https://github.com/microsoft/vcpkg/issues/16019.
on:
  push:
  schedule:
    - cron: 0 0 2 3 *
jobs: 
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
      
    steps:
      - run: |
             git clone https://github.com/microsoft/vcpkg
   
      - name: Build (Linux)
        run: |
             vcpkg/bootstrap-vcpkg.sh
             vcpkg/vcpkg integrate install
             vcpkg/vcpkg list tess
             vcpkg/vcpkg install tesseract:x64-linux
        if: runner.os == 'Linux'
        
      - name: Build (Windows)
        run: |
             vcpkg/bootstrap-vcpkg.bat
             vcpkg/vcpkg integrate install
             vcpkg/vcpkg list tess
             vcpkg/vcpkg install tesseract:x64-windows
        if: runner.os == 'Windows'

